openapi: 3.0.0
info:
  title: 'Search API'
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Current host server
  - url: https:your-server.com
    description: Prod server
paths:
  /v1/movies:
    get:
      summary: 'Get movies'
      description: 'Display all movies.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfMovies'
            application/xml:
              schema:
                $ref: '#/components/schemas/ArrayOfMovies'
            text/plain:
              schema:
                type: string
        '404':
          description: Resource Not Found
      tags:
        - v1
components:
  schemas:
    ArrayOfMovies:
      type: array
      items:
        $ref: '#/components/schemas/Movie'
    Movie:
      type: object
      properties:
        id:
          type: integer
          description: The movie ID.
        title:
          type: string
          description: The movie name.
        release_date:
          type: string
          format: date
          description: The release date of the movie.
        synopsis:
          type: string
          description: The synopsis of the movie.